// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exvvffdijqlcnenoymiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4dnZmZmRpanFsY25lbm95bWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTA3MjEsImV4cCI6MjA2OTUyNjcyMX0.8EJfHENdPkkaMjzZt3CXa2N5Ayv9sU6bdhlFgiMdK64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});